apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-super-project
  namespace: galaxy
spec:
  selector:
    matchLabels:
      app: my-super-project
  replicas: 1
  template:
    metadata:
      labels:
        app: my-super-project
    spec:
      containers:
      - name: my-super-project
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "1"
