apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-app
  namespace: mon-namespace
spec:
  selector:
    matchLabels:
      app: mon-app
  replicas: 1
  template:
    metadata:
      labels:
        app: mon-app
    spec:
      containers:
      - name: mon-app
        image: mon-app:latest
        ports:
        - containerPort: 8080
