apiVersion: apps/v1
kind: Deployment
metadata:
  name: metnimportequoi
  namespace: default
spec:
  selector:
    matchLabels:
      app: metnimportequoi
  replicas: 1
  template:
    metadata:
      labels:
        app: metnimportequoi
    spec:
      containers:
      - name: metnimportequoi
        image: metnimportequoi:latest
        ports:
        - containerPort: 80
