name: add-deployment-k8s
label: 'Add a deployment'
description: 'Add a K8S deployment in Kubernetes'
group: 'Add'

variables:
  - name: name
    label: Name
  - name: namespace
    label: Namespace
  - name: port
    label: Port
    default_value: 80
    
rules:
  - name: add-deployment-k8s
    target: ../deployment.yaml
  - name: add-service-k8s
    target: ../service.yaml